export let responses = [
  "This is gonna be interesting",
  "Hahahahahahaa",
  "You can never beat me",
  "You are just a meh fighter",
  "Meh......Puny God",
  "You are real hard to beat",
  "Such a wusss",
  "Nah, you cant beat me",
  "I own this thing",
  "What a lowly being you are",
  "This is getting interesting",
  "Aaaaahhhhh.....",
  "Baam, there go your skill",
  "Enough talk, lets fight it out",
  "Ohh just look at you all terrified",
  "Such a suck-up",
  "Booom... this how your head will explode",
  "What a shame",
  "You are just a disappointment",
  "My 10-year old niece fights better than you",
  "I will destroy you to the last atom",
  "Nah.. not today my friend",
  "Show some balls and try and win this",
  "Do you just blabber??",
  "There is no chance you get out of here alive",
  "You should go and chase the ice cream truck",
  "I could fight you while sleeping",
  "How's It Feel...",
  "The Last Time You Really Inspired Anyone...",
  "None Of That Made Sense...",
  "Now Change Size...",
  "That's how I roll",
  "You have gotta be kidding me",
  "If you wanna play the kids' section is over there",
  "You have no idea how powerful I am",
  "This isn't some joke going on",
  "I will kill you and take your spouse to dinner",
  "There is very little you can do about this",
  "Lemme show you who is in-charge",
  "Last time i let you go , not this time",
  "Enough banter, lets battle it out",
  "Are you a clown? Cause you are making me laugh",
  "There isn't anything you can do about your doom",
  "After this fight one of us will remain",
  "Over my corpse....",
  "Lets finish this up real quick",
  "What a pathetic move",
  "You are a big baffling buffoon",
  "You should leave the battleground , Right Now!!!",
  "Try and summon more power",
  "Today is my day",
  "You better start taking lessons for this",
  "There is no reason for me to spare you",
  "Wait I am RSVPing to your funeral",
  "There is no way out of here alive",
  "Just get up and pray that i don't end you",
  "Here take this, i found your cape beneath my foot",
  "I am gonna laugh over your corpse",
  "I am gonna defeat in every universe",
  "This fight is gonna be your last",
];
